### ISSUE TITLE
[Infra] Add Load Testing Relays on LocalNet

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#29] opened 2023-10-06 22:47 UTC
## Objective

Conduct multi-faceted load testing on the blockchain, DA layer, and relayer/gateway.

## Goals

- Identify or develop a load-testing tool compatible with our stack (coordinate with Grove team)
- Enable customizable transaction types, frequency, and volume for load tests
- Enable customizable relay frequency and volume for load tests
- Ensure compatibility with LocalNet for testing

## Deliverables

- [ ] Selection or creation of a load-testing tool after consulting with Grove team
- [ ] Implement a feature to customize and trigger load tests for transactions
- [ ] Implement a feature to customize and trigger load tests for relays
- [ ] Validate that the load-testing tool and features are usable on LocalNet

## Non-goals / Non-deliverables

- Though it should be deployable to DevNet, this ticket's scope is LocalNet only

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment] 2023-11-27 22:29
Closing as a duplicate of #135

**Closed by Olshansk** 2023-11-27 22:29 UTC
Labels: infra
